name: uC CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Whoami
      run: whoami
    - name: Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install platformio
    - name: Static Analysis
      run: python3 -m platformio check
    - name: Build
      run: python3 -m platformio run
